"""add referrals

Revision ID: 1bf84fd7f943
Revises: 4b104e2faefc
Create Date: 2025-01-15 05:57:21.799390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bf84fd7f943"
down_revision: Union[str, None] = "4b104e2faefc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("referral_link", sa.String(), nullable=True))
    op.add_column("users", sa.Column("use_referral_link", sa.String(), nullable=True))
    op.drop_column("users", "referal_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("referal_link", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "use_referral_link")
    op.drop_column("users", "referral_link")
    # ### end Alembic commands ###
