"""create new tables

Revision ID: 54810f731614
Revises: d8c2e38cce62
Create Date: 2025-03-01 03:12:49.776416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54810f731614"
down_revision: Union[str, None] = "d8c2e38cce62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bonus_links", sa.Column("active", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "bonus_links", sa.Column("active_count", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bonus_links", "active_count")
    op.drop_column("bonus_links", "active")
    # ### end Alembic commands ###
