"""add gpt asis and username

Revision ID: 2163f4644519
Revises: 7cb4138afb93
Create Date: 2025-03-15 21:23:40.824378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2163f4644519"
down_revision: Union[str, None] = "7cb4138afb93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gpt_assistants", sa.Column("comment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gpt_assistants", "comment")
    # ### end Alembic commands ###
