"""ready user and premium

Revision ID: 4b104e2faefc
Revises: 1e744822c24a
Create Date: 2025-01-15 05:56:19.132665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b104e2faefc"
down_revision: Union[str, None] = "1e744822c24a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("premium_users", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "premium_users", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "premium_users", type_="foreignkey")
    op.drop_column("premium_users", "user_id")
    # ### end Alembic commands ###
