"""create new table & payment promocodes & add last pay

Revision ID: 152e7184df9c
Revises: a0a885dcd0c4
Create Date: 2025-03-27 02:31:50.118676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "152e7184df9c"
down_revision: Union[str, None] = "a0a885dcd0c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_promocodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discount", sa.Integer(), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("count_active", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "premium_users",
        sa.Column("last_pay_count", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("premium_users", "last_pay_count")
    op.drop_table("payment_promocodes")
    # ### end Alembic commands ###
