"""change coun string in message

Revision ID: 749b7c5b6adb
Revises: 152e7184df9c
Create Date: 2025-03-27 03:31:13.711186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "749b7c5b6adb"
down_revision: Union[str, None] = "152e7184df9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "message",
        existing_type=sa.VARCHAR(length=5000),
        type_=sa.String(length=20000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "message",
        existing_type=sa.String(length=20000),
        type_=sa.VARCHAR(length=5000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
