"""add gpt asis and username

Revision ID: c0ab59f3b580
Revises: bb3f8adee1c9
Create Date: 2025-03-15 21:16:36.864419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0ab59f3b580"
down_revision: Union[str, None] = "bb3f8adee1c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gpt_assistants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("assistant_id", sa.String(), nullable=False),
        sa.Column("disable", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assistant_id"),
    )
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    op.drop_table("gpt_assistants")
    # ### end Alembic commands ###
