"""new bonus and first hash

Revision ID: d8c2e38cce62
Revises: a75891e06143
Create Date: 2025-02-24 03:49:59.242382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8c2e38cce62"
down_revision: Union[str, None] = "a75891e06143"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bonus_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("energy_bonus", sa.DECIMAL(precision=15, scale=1), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "generate_images", sa.Column("first_hash", sa.String(), nullable=False)
    )
    op.alter_column(
        "users",
        "energy",
        existing_type=sa.NUMERIC(precision=15, scale=1),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "energy",
        existing_type=sa.NUMERIC(precision=15, scale=1),
        nullable=True,
    )
    op.drop_column("generate_images", "first_hash")
    op.drop_table("bonus_links")
    # ### end Alembic commands ###
