"""add gpt asis and username

Revision ID: 7cb4138afb93
Revises: c0ab59f3b580
Create Date: 2025-03-15 21:18:00.830837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cb4138afb93"
down_revision: Union[str, None] = "c0ab59f3b580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gpt_assistants",
        sa.Column("premium_free", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "gpt_assistants",
        sa.Column("energy_cost", sa.DECIMAL(precision=15, scale=1), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gpt_assistants", "energy_cost")
    op.drop_column("gpt_assistants", "premium_free")
    # ### end Alembic commands ###
