"""add dialog uuid

Revision ID: 8be029dc499a
Revises: 50679890f7db
Create Date: 2025-04-05 15:14:59.401964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = "8be029dc499a"
down_revision: Union[str, None] = "50679890f7db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dialogs",
        sa.Column(
            "uuid",
            sa.UUID(as_uuid=True),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
            unique=True,
        ),
    )
    op.create_index('ix_dialogs_uuid', 'dialogs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dialogs_uuid', table_name='dialogs')
    
    op.drop_column("dialogs", "uuid")
    # ### end Alembic commands ###
