"""last revision

Revision ID: 5a18031b8a9c
Revises: 54810f731614
Create Date: 2025-03-08 05:48:18.446507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a18031b8a9c"
down_revision: Union[str, None] = "54810f731614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "premium_users",
        sa.Column("premium_from_date", sa.Date(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("premium_users", "premium_from_date")
    # ### end Alembic commands ###
