"""add new user energy

Revision ID: 93a6cff8d965
Revises: 1bf84fd7f943
Create Date: 2025-01-15 06:21:34.835342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93a6cff8d965"
down_revision: Union[str, None] = "1bf84fd7f943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "energy",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=15, scale=1),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "energy",
        existing_type=sa.DECIMAL(precision=15, scale=1),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
