"""add gpt asis and username

Revision ID: ce120c4e808c
Revises: 2163f4644519
Create Date: 2025-03-17 07:27:44.217130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce120c4e808c"
down_revision: Union[str, None] = "2163f4644519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gpt_assistants",
        sa.Column("only_for_premium", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gpt_assistants", "only_for_premium")
    # ### end Alembic commands ###
