"""add fours images and energy to generate image

Revision ID: 0127bd4cd44a
Revises: 9227dafbfc23
Create Date: 2025-04-09 13:37:14.134446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0127bd4cd44a"
down_revision: Union[str, None] = "9227dafbfc23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    new_enum = sa.Enum(
        "CLAUDE_VERSION_SONNET",
        "CLAUDE_VERSION_SONNET37",
        "CLAUDE_VERSION_HAIKU35",
        name="claudeconfig_new"
    )
    new_enum.create(op.get_bind(), checkfirst=True)
    
    op.alter_column(
        "user_config",
        "claude_select",
        type_=new_enum,
        postgresql_using="claude_select::text::claudeconfig_new"
    )
    
    op.execute("DROP TYPE claudeconfig")
    
    # Переименовываем временный enum в оригинальное имя
    op.execute("ALTER TYPE claudeconfig_new RENAME TO claudeconfig")
    
    op.add_column(
        "generate_images",
        sa.Column(
            "energy_cost", sa.DECIMAL(precision=15, scale=1), nullable=True
        ),
    )
    op.add_column(
        "generate_images", sa.Column("first_image", sa.String(), nullable=True)
    )
    op.add_column(
        "generate_images", sa.Column("original_prompt", sa.String(), nullable=True)
    )
    op.add_column(
        "generate_images",
        sa.Column("second_image", sa.String(), nullable=True),
    )
    op.add_column(
        "generate_images", sa.Column("third_image", sa.String(), nullable=True)
    )
    op.add_column(
        "generate_images",
        sa.Column("fourth_image", sa.String(), nullable=True),
    )
    op.alter_column(
        "payment_promocodes",
        "discount",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_promocodes",
        "discount",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("generate_images", "fourth_image")
    op.drop_column("generate_images", "third_image")
    op.drop_column("generate_images", "second_image")
    op.drop_column("generate_images", "first_image")
    op.drop_column("generate_images", "energy_cost")
    
    old_enum = sa.Enum(
        "CLAUDE_VERSION_SONNET",
        "CLAUDE_VERSION_SONNET37",
        name="claudeconfig_old"
    )
    old_enum.create(op.get_bind(), checkfirst=True)
    
    # Изменяем тип столбца на временный enum
    op.alter_column(
        "user_config",
        "claude_select",
        type_=old_enum,
        postgresql_using="CASE "
                         "WHEN claude_select = 'CLAUDE_VERSION_SONNET' THEN 'CLAUDE_VERSION_SONNET'::claudeconfig_old "
                         "ELSE 'CLAUDE_VERSION_SONNET'::claudeconfig_old "
                         "END"
    )
    
    # Удаляем новый enum
    op.execute("DROP TYPE claudeconfig")
    
    # Переименовываем временный enum в оригинальное имя
    op.execute("ALTER TYPE claudeconfig_old RENAME TO claudeconfig")
    # ### end Alembic commands ###
