"""add midjourney speed settings

Revision ID: 50679890f7db
Revises: a37d0402b4ef
Create Date: 2025-03-31 01:28:16.291866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50679890f7db"
down_revision: Union[str, None] = "a37d0402b4ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    sa.Enum("RELAX", "FAST", "TURBO", name="midjourneyspeedconfig").create(
        op.get_bind()
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_config",
        sa.Column(
            "midjourney_speed",
            sa.Enum("RELAX", "FAST", "TURBO", name="midjourneyspeedconfig"),
            server_default="RELAX",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_config", "midjourney_speed")
    sa.Enum(name="midjourneyspeedconfig").drop(op.get_bind())
    # ### end Alembic commands ###
